version: "3.8"

services:
  systemcall-practice:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systemcall_practice_container
    volumes:
      - ./scripts:/scripts:rw
    working_dir: /scripts
    stdin_open: true
    tty: true
    command: /bin/bash
